import type { Metadata } from 'next';
import '../styles/globals.css';
import { Inter, DM_Sans } from 'next/font/google';
import { Providers } from '../store/providers';
import { Toaster } from 'sonner';
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const dmsans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dmsans',
});
export const metadata: Metadata = {
  title: 'MavenMd-Frontend',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${dmsans.variable}`}>
      <body>
        <Providers>
          {children}
          <Toaster richColors position="bottom-right" />
        </Providers>
      </body>
    </html>
  );
}
